### ISSUE TITLE
unable to get harmonauts

### ISSUE THREAD

**Issue by chriscrutt** [ivorytowerdds/harmonauts#16]
Shouldn't it be `if (allHarmonautsAssigned) throw;`
Because right now (below) you have ` if (!allHarmonautsAssigned) throw;` which means if all Harmonauts ***are not*** assigned, you can't get any- which is counterintuitive
```
function getHarmonaut(uint HarmonautIndex) {
        if (!allHarmonautsAssigned) throw;
        if (HarmonautsRemainingToAssign == 0) throw;
        if (HarmonautIndexToAddress[HarmonautIndex] != 0x0) throw;
        if (HarmonautIndex >= 1000) throw;
        HarmonautIndexToAddress[HarmonautIndex] = msg.sender;
        balanceOf[msg.sender]++;
        HarmonautsRemainingToAssign--;
        Assign(msg.sender, HarmonautIndex);
    }
```

**Comment by ivorytowerdds** [comment]
Hi Chris, it's a good question. This project is sourced from an existing project on Ethereum - cryptopunks, an open source project. We are building it for technology demonstration, and not for commercial purposes.
We kept the logistics of this part. So the following is based on my own understanding. 

First, only if you call the function `allInitialOwnersAssigned()`, the variable `allHarmanoutsAssigned` will be `True`, so it's just a flag you, the owner can control. 

Second, the logistic of `getHarmonaut` only happens in the very beginning of the project - "claim harmonaut for free, based on 'first come first serve' rule". It will not impact the later process of buying and selling harmonaut. Now let's talk about the initial claim process, there are two ways you can do. First, as owner, you directly set the ownerships to others, where `setInitialOwner` and `setInitialOwners` function apply. Second is participates can come to claim by themselves, and they will click button or anything but the code behind the button is calling this function. I agree what you said, it's counterintuitive to me too. One of the reasons I think why the author of the cryptopunks designed like this is you want to set up a starting time for people to join the claim game for fair. By add this constraint, you, the owner can control the start time by calling  `allInitialOwnersAssigned()`. Before you do that, no one can claim. 

But this is just my thought. And I think to make it more clear, maybe we should have better naming for the function or just delete this function. It will be fine since we can still use the first method to set the initial owners. And deleting this function will not impact how people buy and sell the harmonauts. Hope it helps!

**Comment by chriscrutt** [comment]
ahhhh, so calling `allInitialOwnersAssigned()` is just saying everything is set up the way they want it before they allow the public to redeem other punks/harmonauts. Thus, someone could call `getPunk()` after the previous function has been called.

**Comment by chriscrutt** [comment]
lemme know when you decide to open it up to the public @ivorytowerdds

**Comment by ivorytowerdds** [comment]
> ahhhh, so calling `allInitialOwnersAssigned()` is just saying everything is set up the way they want it before they allow the public to redeem other punks/harmonauts. Thus, someone could call `getPunk()` after the previous function has been called.

yes, that's my understanding.
